# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-16 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sulg',
            field=models.SlugField(default='abc'),
        ),
    ]
