# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-16 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_sulg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sulg',
            field=models.SlugField(blank=True, default='abc', null=True),
        ),
    ]
