# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-16 12:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20181016_1235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sulg',
            new_name='slug',
        ),
    ]
