# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-16 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20181016_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, default='abc', null=True, unique=True),
        ),
    ]
